[package]
name = "nia"
version = "0.1.0"
edition = "2024"

[dependencies]
atom_syndication = "0.12.7"
chrono = { version = "0.4.43", features = ["now"] }
crossterm = "0.29.0"
linkify = "0.10.0"
ratatui = "0.30.0"
reqwest = { version = "0.13.2", features = ["blocking"] }
rss = "2.0.12"
url = "2.5.8"
